package mime

type mimeType struct {
	name     string
	patterns []string
}

var registry = []*mimeType{
	{"image/bmp", []string{"*.bmp"}},
	{"image/g3fax", []string{"*.g3"}},
	{"image/gif", []string{"*.gif"}},
	{"image/jpeg", []string{"*.jpeg", "*.jpg", "*.jpe"}},
	{"image/png", []string{"*.png"}},
	{"image/tiff", []string{"*.tif", "*.tiff"}},
	{"image/vnd.adobe.photoshop", []string{"*.psd"}},
	{"image/vnd.djvu", []string{"*.djv", "*.djvu"}},
	{"image/vnd.dwg", []string{"*.dwg"}},
	{"image/vnd.fpx", []string{"*.fpx"}},
	{"image/vnd.microsoft.icon", []string{"*.ico"}},
	{"image/webp", []string{"*.webp"}},
	{"image/x-3ds", []string{"*.3ds"}},
	{"image/x-canon-cr2", []string{"*.cr2"}},
	{"image/x-canon-crw", []string{"*.crw"}},
	{"image/x-ms-bmp", []string{"*.bmp"}},
	{"image/x-olympus-orf", []string{"*.orf"}},
	{"image/x-pcx", []string{"*.pcx"}},
	{"image/x-portable-bitmap", []string{"*.pbm"}},
	{"image/x-portable-pixmap", []string{"*.ppm"}},
	{"image/x-tga", []string{"*.tga"}},
	{"image/x-xwindowdump", []string{"*.xwd"}},
	{"image/cgm", []string{"*.cgm"}},
	{"image/ief", []string{"*.ief"}},
	{"image/ktx", []string{"*.ktx"}},
	{"image/pcx", []string{"*.pcx"}},
	{"image/prs.btif", []string{"*.btif"}},
	{"image/sgi", []string{"*.sgi"}},
	{"image/vnd.dece.graphic", []string{"*.uvg", "*.uvi", "*.uvvg", "*.uvvi"}},
	{"image/vnd.dvb.subtitle", []string{"*.sub"}},
	{"image/vnd.dxf", []string{"*.dxf"}},
	{"image/vnd.fastbidsheet", []string{"*.fbs"}},
	{"image/vnd.fst", []string{"*.fst"}},
	{"image/vnd.fujixerox.edmics-mmr", []string{"*.mmr"}},
	{"image/vnd.fujixerox.edmics-rlc", []string{"*.rlc"}},
	{"image/vnd.ms-modi", []string{"*.mdi"}},
	{"image/vnd.ms-photo", []string{"*.wdp"}},
	{"image/vnd.net-fpx", []string{"*.npx"}},
	{"image/vnd.wap.wbmp", []string{"*.wbmp"}},
	{"image/vnd.xiff", []string{"*.xif"}},
	{"image/x-cmu-raster", []string{"*.ras"}},
	{"image/x-cmx", []string{"*.cmx"}},
	{"image/x-coreldraw", []string{"*.cdr"}},
	{"image/x-coreldrawpattern", []string{"*.pat"}},
	{"image/x-coreldrawtemplate", []string{"*.cdt"}},
	{"image/x-corelphotopaint", []string{"*.cpt"}},
	{"image/x-epson-erf", []string{"*.erf"}},
	{"image/x-freehand", []string{"*.fh", "*.fh4", "*.fh5", "*.fh7", "*.fhc"}},
	{"image/x-icon", []string{"*.ico"}},
	{"image/x-jg", []string{"*.art"}},
	{"image/x-jng", []string{"*.jng"}},
	{"image/x-mrsid-image", []string{"*.sid"}},
	{"image/x-nikon-nef", []string{"*.nef"}},
	{"image/x-photoshop", []string{"*.psd"}},
	{"image/x-pict", []string{"*.pct", "*.pic"}},
	{"image/x-portable-anymap", []string{"*.pnm"}},
	{"image/x-portable-graymap", []string{"*.pgm"}},
	{"image/x-rgb", []string{"*.rgb"}},
	{"image/x-xbitmap", []string{"*.xbm"}},
	{"image/x-xpixmap", []string{"*.xpm"}},
	{"video/3gpp", []string{"*.3gp"}},
	{"video/3gpp2", []string{"*.3g2"}},
	{"video/MP2T", []string{"*.ts"}},
	{"video/mj2", []string{"*.mj2", "*.mjp2"}},
	{"video/mp4", []string{"*.mp4", "*.mp4v", "*.mpg4"}},
	{"video/mpeg", []string{"*.mpeg", "*.m1v", "*.m2v", "*.mpe", "*.mpg"}},
	{"video/ogg", []string{"*.ogv"}},
	{"video/quicktime", []string{"*.mov", "*.qt"}},
	{"video/vnd.dvb.file", []string{"*.dvb"}},
	{"video/webm", []string{"*.webm"}},
	{"video/x-fli", []string{"*.fli"}},
	{"video/x-flv", []string{"*.flv"}},
	{"video/x-m4v", []string{"*.m4v"}},
	{"video/x-matroska", []string{"*.mkv", "*.mk3d", "*.mks", "*.mpv"}},
	{"video/x-mng", []string{"*.mng"}},
	{"video/x-ms-asf", []string{"*.asf", "*.asx"}},
	{"video/x-msvideo", []string{"*.avi"}},
	{"video/x-sgi-movie", []string{"*.movie"}},
	{"video/annodex", []string{"*.axv"}},
	{"video/dl", []string{"*.dl"}},
	{"video/dv", []string{"*.dif", "*.dv"}},
	{"video/fli", []string{"*.fli"}},
	{"video/gl", []string{"*.gl"}},
	{"video/h261", []string{"*.h261"}},
	{"video/h263", []string{"*.h263"}},
	{"video/h264", []string{"*.h264"}},
	{"video/jpeg", []string{"*.jpgv"}},
	{"video/jpm", []string{"*.jpgm", "*.jpm"}},
	{"video/vnd.dece.hd", []string{"*.uvh", "*.uvvh"}},
	{"video/vnd.dece.mobile", []string{"*.uvm", "*.uvvm"}},
	{"video/vnd.dece.pd", []string{"*.uvp", "*.uvvp"}},
	{"video/vnd.dece.sd", []string{"*.uvs", "*.uvvs"}},
	{"video/vnd.dece.video", []string{"*.uvv", "*.uvvv"}},
	{"video/vnd.fvt", []string{"*.fvt"}},
	{"video/vnd.mpegurl", []string{"*.m4u", "*.mxu"}},
	{"video/vnd.ms-playready.media.pyv", []string{"*.pyv"}},
	{"video/vnd.uvvu.mp4", []string{"*.uvu", "*.uvvu"}},
	{"video/vnd.vivo", []string{"*.viv"}},
	{"video/x-f4v", []string{"*.f4v"}},
	{"video/x-la-asf", []string{"*.lsf", "*.lsx"}},
	{"video/x-ms-vob", []string{"*.vob"}},
	{"video/x-ms-wm", []string{"*.wm"}},
	{"video/x-ms-wmv", []string{"*.wmv"}},
	{"video/x-ms-wmx", []string{"*.wmx"}},
	{"video/x-ms-wvx", []string{"*.wvx"}},
	{"video/x-smv", []string{"*.smv"}},
}
